### ISSUE TITLE
Difference with alx-folder-note

### ISSUE THREAD

**Issue by Mara-Li** [alangrainger/obsidian-folder-notes#1]
Hello.
I want to know what are the difference between this plugin and the plugin [alx-folder-note](https://github.com/aidenlx/alx-folder-note) ? 
alx-folder-note provide multiple options and only the core plugin can be used to keep a minimal behavior.

**Comment by alangrainger** [comment]
Alx-folder-note doesn't appear to do anything useful for me. 

Here it is installed in the Sandbox vault, and I'm clicking into a folder with an exactly-named folder note - and nothing happens.

Can you confirm that alx-folder-note actually does anything?

![Obsidian_xYScTGKpUa](https://user-images.githubusercontent.com/16197738/211170001-de7e863c-a446-41df-b252-18c61228ed3f.gif)

**Comment by alangrainger** [comment]
It gets worse. If I install both of these, I lose the ability to open my folders:

![image](https://user-images.githubusercontent.com/16197738/211170587-753fc799-e4b9-4bb1-a4dc-274430bbe1aa.png)

![Obsidian_AahMR4JzB9](https://user-images.githubusercontent.com/16197738/211170599-2e6457bd-4635-4e5d-8905-aafa592b6524.gif)

So I would say the difference between this and alx-folder-notes is that it has no bloat, and actually functions.

**Comment by alangrainger** [comment]
...... mainly the difference is that the docs in "Folder Note Core" do **not** make it clear that you also need the "AidenLx's Folder Note" plugin for the "Folder Note Core" plugin to work.

I thought it wasn't functional, because I hadn't installed the "AidenLx's Folder Note" plugin also.

🤦‍♂️

So you can probably close the pull request on this. I won't use Alx myself as I don't want all the extra bloat, but perhaps my plugin isn't necessary.

If you don't mind, I would **love** some feedback on the efficiency of my code for hooking into to the folder tree clicks. Is this a sensible way to approach the problem, or is it wasteful to watch all mutations that way?
